#PARAM MONDE
WIDTH: int = 20 # COL
HEIGHT: int = 10 # ROW

#PARAM POOULATION
NB_TUNA: int = 5
NB_SHARK: int = 5

#PARAM REPRODUCTION
TUNA_REPRODUCTION_TIME: int = 1
SHARK_REPRODUCTION_TIME: int = 1

#PARAM ENERGY
SHARK_ENERGY: int = 5

TIK = 0.8
