#PARAM MONDE
WIDTH: int = 30
HEIGHT: int = 30

#PARAM POPULATION
NB_TUNA: int = 10
NB_SHARK: int = 10

#PARAM REPRODUCTION
TUNA_REPRODUCTION_TIME: int = 5
SHARK_REPRODUCTION_TIME: int = 5

#PARAM ENERGY
SHARK_ENERGY: int = 5
SHARK_ENERGY_GAIN: int = 1
