#PARAM MONDE
WIDTH: int = 30
HEIGHT: int = 30

#PARAM POPULATION
NB_TUNA: int = 150
NB_SHARK: int = 40

#PARAM REPRODUCTION
TUNA_REPRODUCTION_TIME: int = 4
SHARK_REPRODUCTION_TIME: int = 8

#PARAM ENERGY
SHARK_ENERGY: int = 10
SHARK_ENERGY_GAIN: int = 4
